<?php

/**
 * @file
 * Install, update and uninstall functions for the Notification to the Parties module.
 */

/**
 * Implements hook_install().
 */
function parties_notification_install() {
  if (module_exists('entity_translation')) {
    variable_set('language_content_type_parties_notification', ENTITY_TRANSLATION_ENABLED);
    variable_set('entity_translation_hide_translation_links_parties_notification', 1);

    $et_settings_node = variable_get('entity_translation_settings_node__parties_notification');

    $et_settings_node['default_language']       = ENTITY_TRANSLATION_LANGUAGE_DEFAULT;
    $et_settings_node['hide_language_selector'] = FALSE;

    variable_set('entity_translation_settings_node__parties_notification', $et_settings_node);
  }
}
